In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from sklearn.datasets import make_classification

x, y = make_classification(
    n_samples=1000, # 1000 observations
    n_classes=2,    # binary target/features
    n_features=3,   # total features
    n_redundant=1,
    random_state=999
)

In [4]:
x

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]], shape=(1000, 3))

In [5]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [6]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=5, algorithm='auto')
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

In [7]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print("Confusion Matrix")
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

Confusion Matrix
[[158  20]
 [ 11 141]]
0.906060606060606
              precision    recall  f1-score   support

           0       0.93      0.89      0.91       178
           1       0.88      0.93      0.90       152

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330



In [8]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'metric': ['euclidean', 'manhattan', 'minkowski']
}

grid = GridSearchCV(KNeighborsClassifier(),param_grid=param_grid,refit=True,cv=5,verbose=3)

In [9]:
grid.fit(x_train, y_train)
y_pred = grid.predict(x_test)

Fitting 5 folds for each of 240 candidates, totalling 1200 fits
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=1, weights=uniform;, score=0.873 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=1, weights=uniform;, score=0.903 total time=   0.1s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=1, weights=uniform;, score=0.866 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean, n_neighbors=1, weights=uniform;, score=0.858 total time=   0.0s
[CV 5/5] END algorithm=auto, metric=euclidean, n_neighbors=1, weights=uniform;, score=0.888 total time=   0.0s
[CV 1/5] END algorithm=auto, metric=euclidean, n_neighbors=1, weights=distance;, score=0.873 total time=   0.0s
[CV 2/5] END algorithm=auto, metric=euclidean, n_neighbors=1, weights=distance;, score=0.903 total time=   0.0s
[CV 3/5] END algorithm=auto, metric=euclidean, n_neighbors=1, weights=distance;, score=0.866 total time=   0.0s
[CV 4/5] END algorithm=auto, metric=euclidean

In [10]:
grid.best_params_

{'algorithm': 'auto',
 'metric': 'euclidean',
 'n_neighbors': 9,
 'weights': 'uniform'}

In [11]:
print("Confusion Matrix")
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

Confusion Matrix
[[156  16]
 [ 13 145]]
0.9121212121212121
              precision    recall  f1-score   support

           0       0.92      0.91      0.91       172
           1       0.90      0.92      0.91       158

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330

